// @generated
// This file is @generated by prost-build.
/// Parsed Jupiter swap data with amounts
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapData {
    #[prost(string, tag="1")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub input_mint: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub output_mint: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub amount_in: u64,
    #[prost(uint64, tag="6")]
    pub amount_out: u64,
    #[prost(uint64, tag="7")]
    pub minimum_amount_out: u64,
    #[prost(string, tag="8")]
    pub user_wallet: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub slot: u64,
    #[prost(uint64, tag="10")]
    pub block_time: u64,
    /// "route", "shared_accounts_route", "exact_out", etc.
    #[prost(string, tag="11")]
    pub swap_type: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapDataList {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<SwapData>,
    #[prost(uint64, tag="2")]
    pub total_volume_in: u64,
    #[prost(uint64, tag="3")]
    pub total_volume_out: u64,
    #[prost(uint32, tag="4")]
    pub swap_count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingData {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub accounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub slot: u64,
    #[prost(uint64, tag="6")]
    pub block_time: u64,
    /// Parsed swap fields
    #[prost(uint64, tag="7")]
    pub amount_in: u64,
    #[prost(uint64, tag="8")]
    pub amount_out: u64,
    #[prost(string, tag="9")]
    pub input_mint: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub output_mint: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub user_wallet: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPrice {
    #[prost(string, tag="1")]
    pub mint_address: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub price_usd: f64,
    #[prost(double, tag="3")]
    pub volume_24h: f64,
    #[prost(double, tag="4")]
    pub price_change_24h: f64,
    #[prost(uint64, tag="5")]
    pub slot: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrichedAccount {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub mint: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountOwnerRecord {
    #[prost(bytes="vec", tag="1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountOwnerRecords {
    #[prost(message, repeated, tag="1")]
    pub records: ::prost::alloc::vec::Vec<AccountOwnerRecord>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingDataList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<TradingData>,
    #[prost(uint64, tag="2")]
    pub total_volume: u64,
    #[prost(uint32, tag="3")]
    pub swap_count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPriceList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<TokenPrice>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterInstruction {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub accounts: ::prost::alloc::vec::Vec<EnrichedAccount>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub slot: u64,
    #[prost(uint64, tag="6")]
    pub block_time: u64,
    /// Parsed swap data
    #[prost(uint64, tag="7")]
    pub amount_in: u64,
    #[prost(uint64, tag="8")]
    pub amount_out: u64,
    #[prost(string, tag="9")]
    pub input_mint: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub output_mint: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterInstructions {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<JupiterInstruction>,
    #[prost(uint64, tag="2")]
    pub total_volume: u64,
    #[prost(uint32, tag="3")]
    pub instruction_count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProgramStat {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub instruction_count: u64,
    #[prost(uint64, tag="3")]
    pub total_volume: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterAnalytics {
    #[prost(uint64, tag="1")]
    pub total_instructions: u64,
    #[prost(uint64, tag="2")]
    pub unique_accounts: u64,
    #[prost(uint64, tag="3")]
    pub unique_mints: u64,
    #[prost(message, repeated, tag="4")]
    pub top_programs: ::prost::alloc::vec::Vec<ProgramStat>,
    #[prost(uint64, tag="5")]
    pub total_volume: u64,
    #[prost(uint64, tag="6")]
    pub total_swaps: u64,
}
// @@protoc_insertion_point(module)
