// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingData {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub accounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub slot: u64,
    #[prost(uint64, tag="6")]
    pub block_time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPrice {
    #[prost(string, tag="1")]
    pub mint_address: ::prost::alloc::string::String,
    #[prost(double, tag="2")]
    pub price_usd: f64,
    #[prost(double, tag="3")]
    pub volume_24h: f64,
    #[prost(double, tag="4")]
    pub price_change_24h: f64,
    #[prost(uint64, tag="5")]
    pub slot: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrichedAccount {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub mint: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountOwnerRecord {
    #[prost(bytes="vec", tag="1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountOwnerRecords {
    #[prost(message, repeated, tag="1")]
    pub records: ::prost::alloc::vec::Vec<AccountOwnerRecord>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingDataList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<TradingData>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPriceList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<TokenPrice>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterInstruction {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub accounts: ::prost::alloc::vec::Vec<EnrichedAccount>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub slot: u64,
    #[prost(uint64, tag="6")]
    pub block_time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterInstructions {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<JupiterInstruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProgramStat {
    #[prost(string, tag="1")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub instruction_count: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JupiterAnalytics {
    #[prost(uint64, tag="1")]
    pub total_instructions: u64,
    #[prost(uint64, tag="2")]
    pub unique_accounts: u64,
    #[prost(uint64, tag="3")]
    pub unique_mints: u64,
    #[prost(message, repeated, tag="4")]
    pub top_programs: ::prost::alloc::vec::Vec<ProgramStat>,
}
// @@protoc_insertion_point(module)
